### ISSUE TITLE
Problem installing via brew, on Darwin kernel version 23.5.0 with arm x86_64

### ISSUE THREAD

**Issue by AriannaBi** [black-sat/homebrew-black#3] opened 2024-06-08 08:42 UTC
==> Fetching black-sat/black/black-sat
==> Downloading https://github.com/black-sat/black/archive/v0.10.6.tar.gz
==> Downloading from https://codeload.github.com/black-sat/black/tar.gz/refs/tags/v0.10.6
    #     #     #        #                                                                                                       -=O=-                              
==> Installing black-sat from black-sat/black
==> cmake . -DENABLE_MINISAT=NO
==> make
Last 15 lines from /Users/name/Library/Logs/Homebrew/black-sat/02.make:
make[2]: *** [src/lib/CMakeFiles/black.dir/src/solver/core.cpp.o] Error 1
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/semantics.cpp.o] Error 1
6 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/logic.cpp.o] Error 1
6 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/solver/solver.cpp.o] Error 1
/tmp/black-sat-20240608-45292-kns9jp/black-0.10.6/src/lib/src/solver/encoding.cpp:672:5: error: 'switch' missing 'default' label [-Werror,-Wswitch-default]
  672 |     switch(req.type) {
      |     ^
6 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/prettyprint.cpp.o] Error 1
10 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/solver/encoding.cpp.o] Error 1
make[1]: *** [src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/black-sat/homebrew-black/issues

**Comment by nicola-gigante** [comment] 2024-06-08 18:59
Hi! Thanks for reporting. This is likely an incompatibility with a new version of the compiler. 

I’m currently almost offline for another ten days aprox. Then I’ll take care of this!

**Comment by nicola-gigante** [comment] 2024-06-20 12:59
Hi @AriannaBi, I came back to work and now the issue is fixed with the new 0.10.7 release. You may want to try again to install BLACK with Homebrew. Thanks for reporting!

**Closed as completed by nicola-gigante** 2024-06-20 12:59 UTC
